# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./ShAxis.h \
    ./ShDirectoryManager.h \
    ./ShDraft.h \
    ./ShLayer.h \
    ./ShLayerTable.h \
    ./ShMath.h \
    ./ShNotifyEvent.h \
    ./ShPropertyData.h \
    ./ShSelectedEntityManager.h \
    ./ShVariable.h \
    ./ShPoint.h \
    ./ShRibbon.h \
    ./Entity/ShEntity.h \
    ./Entity/ShEntityData.h \
    ./Entity/Leaf/ShArc.h \
    ./Entity/Leaf/ShCircle.h \
    ./Entity/Leaf/ShLeaf.h \
    ./Entity/Leaf/ShLine.h \
    ./Entity/Leaf/ShRubberBand.h \
    ./Entity/Composite/ShComposite.h \
    ./Entity/Composite/ShEntityTable.h \
    ./Entity/Composite/ShPolyLine.h \
    ./Entity/Composite/ShPreview.h \
    ./Interface/ShGraphicView.h \
    ./Interface/ShStatusBar.h \
    ./Interface/shcad.h \
    ./Interface/Dock/ShCommandDock.h \
    ./Interface/Ribbon/ShRibbonMenu.h \
    ./Interface/Ribbon/ShHomeTab.h \
    ./Interface/ToolBar/ShAbstractToolBar.h \
    ./Interface/ToolBar/ShDrawToolBar.h \
    ./Interface/ToolBar/ShModifyToolBar.h \
    ./Interface/ToolBar/ShObjectSnapToolBar.h \
    ./Interface/ToolBar/ShToolBarContainer.h \
    ./Interface/ToolBar/ShPropertyToolBar.h \
    ./Interface/ToolBar/ShLayerToolBar.h \
    ./Interface/Items/ShCustomizedWidget.h \
    ./Interface/Items/ShColorComboBox.h \
    ./Interface/Items/ShLineStyleComboBox.h \
    ./Interface/Items/ShLayerComboBox.h \
    ./Interface/Items/ShRibbonButton.h \
    ./Interface/Dialog/ShLayerDialog.h \
    ./Interface/Dialog/ShPlotDialog.h \
    ./Interface/Dialog/ShPreviewDialog.h \
    ./Interface/Menu/ShMenu.h \
    ./Interface/Menu/ShMenuBar.h \
    ./Visitor Pattern/ShExtender.h \
    ./Visitor Pattern/ShLineBothPerpendicularVisitor.h \
    ./Visitor Pattern/ShFootOfPerpendicularVisitor.h \
    ./Visitor Pattern/ShDrawer.h \
    ./Visitor Pattern/ShFinder.h \
    ./Visitor Pattern/ShHitTester.h \
    ./Visitor Pattern/ShMirror.h \
    ./Visitor Pattern/ShPrintVisitor.h \
    ./Visitor Pattern/ShRotater.h \
    ./Visitor Pattern/ShSnapPointFinder.h \
    ./Visitor Pattern/ShStretchVisitor.h \
    ./Visitor Pattern/ShTrimer.h \
    ./Visitor Pattern/ShVisitor.h \
    ./ActionHandler/ShActionHandler.h \
    ./ActionHandler/ShActionHandlerManager.h \
    ./ActionHandler/ShActionHandlerDecorator.h \
    ./ActionHandler/ShDefaultAction.h \
    ./ActionHandler/ShPlotAreaSelectAction.h \
    ./ActionHandler/DrawAction/ShDrawAction.h \
    ./ActionHandler/DrawAction/ShDrawArcAction.h \
    ./ActionHandler/DrawAction/ShDrawCircleAction.h \
    ./ActionHandler/DrawAction/ShDrawLineAction.h \
    ./ActionHandler/DrawAction/ShDrawPolyLineAction.h \
    ./ActionHandler/TemporaryAction/ShDragSelectAction.h \
    ./ActionHandler/TemporaryAction/ShPanMoveAction.h \
    ./ActionHandler/TemporaryAction/ShStretchTemporaryAction.h \
    ./ActionHandler/TemporaryAction/ShTemporaryAction.h \
    ./ActionHandler/ModifyAction/ShModifyAction.h \
    ./ActionHandler/ModifyAction/ShModifyCopyAction.h \
    ./ActionHandler/ModifyAction/ShModifyEraseAction.h \
    ./ActionHandler/ModifyAction/ShModifyExtendAction.h \
    ./ActionHandler/ModifyAction/ShModifyMirrorAction.h \
    ./ActionHandler/ModifyAction/ShModifyMoveAction.h \
    ./ActionHandler/ModifyAction/ShModifyRotateAction.h \
    ./ActionHandler/ModifyAction/ShModifyStretchAction.h \
    ./ActionHandler/ModifyAction/ShModifyTrimAction.h \
    ./FactoryMethod/ShCreatorActionFactory.h \
    ./FactoryMethod/ShCreatorActionDecoratorFactory.h \
    ./FactoryMethod/ShCreatorObjectSnapFactory.h \
    ./FactoryMethod/ShCreatorViewDrawFactory.h \
    ./FactoryMethod/ShCreatorViewUpdateFactory.h \
    ./Singleton Pattern/ShChangeManager.h \
    ./Singleton Pattern/ShColorComboList.h \
    ./Singleton Pattern/ShDraftManager.h \
    ./Singleton Pattern/ShLineStyleComboList.h \
    ./Singleton Pattern/ShPrinterManager.h \
    ./Singleton Pattern/ShWidgetManager.h \
    ./Command Pattern/ShCommand.h \
    ./Command Pattern/ShRedoTaker.h \
    ./Command Pattern/ShUndoTaker.h \
    ./Command Pattern/Entity Command/ShAddEntityCommand.h \
    ./Command Pattern/Entity Command/ShChangeEntityLayerCommand.h \
    ./Command Pattern/Entity Command/ShChangeEntityPropertyDataCommand.h \
    ./Command Pattern/Entity Command/ShCopyEntityCommand.h \
    ./Command Pattern/Entity Command/ShDeleteEntityCommand.h \
    ./Command Pattern/Entity Command/ShExtendEntityCommand.h \
    ./Command Pattern/Entity Command/ShMirrorEntityCommand.h \
    ./Command Pattern/Entity Command/ShMoveEntityCommand.h \
    ./Command Pattern/Entity Command/ShRotateEntityCommand.h \
    ./Command Pattern/Entity Command/ShStretchEntityCommand.h \
    ./Command Pattern/Entity Command/ShTrimEntityCommand.h \
    ./Command Pattern/UI Command/ShChangeCurrentLayerCommand.h \
    ./Command Pattern/UI Command/ShChangeLayerDataCommand.h \
    ./Command Pattern/UI Command/ShChangePropertyDataCommand.h \
    ./Command Pattern/UI Command/ShCreateLayerCommand.h \
    ./Command Pattern/UI Command/ShDeleteLayerCommand.h \
    ./Command Pattern/UI Command/ShMoveViewCommand.h \
    ./Strategy Pattern/ShButtonWithMenuPopupStrategy.h \
    ./Strategy Pattern/ShChangeCurrentActionStrategy.h \
    ./Strategy Pattern/ShObjectSnapStrategy.h \
    ./Strategy Pattern/ShSearchEntityStrategy.h \
    ./Strategy Pattern/ShViewDrawStrategy.h \
    ./Strategy Pattern/ShViewNotifyEventUpdateStrategy.h \
    ./Facade Pattern/ShCadFacade.h
SOURCES += ./main.cpp \
    ./ShAxis.cpp \
    ./ShDirectoryManager.cpp \
    ./ShLayer.cpp \
    ./ShLayerTable.cpp \
    ./ShMath.cpp \
    ./ShNotifyEvent.cpp \
    ./ShPropertyData.cpp \
    ./ShRibbon.cpp \
    ./ShSelectedEntityManager.cpp \
    ./ShPoint.cpp \
    ./Entity/ShEntity.cpp \
    ./Entity/ShEntityData.cpp \
    ./Entity/Leaf/ShArc.cpp \
    ./Entity/Leaf/ShCircle.cpp \
    ./Entity/Leaf/ShLeaf.cpp \
    ./Entity/Leaf/ShLine.cpp \
    ./Entity/Leaf/ShRubberBand.cpp \
    ./Entity/Composite/ShComposite.cpp \
    ./Entity/Composite/ShEntityTable.cpp \
    ./Entity/Composite/ShPolyLine.cpp \
    ./Entity/Composite/ShPreview.cpp \
    ./Interface/shcad.cpp \
    ./Interface/ShGraphicView.cpp \
    ./Interface/ShStatusBar.cpp \
    ./Interface/Dock/ShCommandDock.cpp \
    ./Interface/Ribbon/ShHomeTab.cpp \
    ./Interface/Ribbon/ShRibbonMenu.cpp \
    ./Interface/ToolBar/ShAbstractToolBar.cpp \
    ./Interface/ToolBar/ShDrawToolBar.cpp \
    ./Interface/ToolBar/ShLayerToolBar.cpp \
    ./Interface/ToolBar/ShModifyToolBar.cpp \
    ./Interface/ToolBar/ShObjectSnapToolBar.cpp \
    ./Interface/ToolBar/ShPropertyToolBar.cpp \
    ./Interface/ToolBar/ShToolBarContainer.cpp \
    ./Interface/Items/ShColorComboBox.cpp \
    ./Interface/Items/ShCustomizedWidget.cpp \
    ./Interface/Items/ShLayerComboBox.cpp \
    ./Interface/Items/ShLineStyleComboBox.cpp \
    ./Interface/Items/ShRibbonButton.cpp \
    ./Interface/Dialog/ShLayerDialog.cpp \
    ./Interface/Dialog/ShPlotDialog.cpp \
    ./Interface/Dialog/ShPreviewDialog.cpp \
    ./Interface/Menu/ShMenu.cpp \
    ./Interface/Menu/ShMenuBar.cpp \
    ./Visitor Pattern/ShExtender.cpp \
    ./Visitor Pattern/ShLineBothPerpendicularVisitor.cpp \
    ./Visitor Pattern/ShFootOfPerpendicularVisitor.cpp \
    ./Visitor Pattern/ShDrawer.cpp \
    ./Visitor Pattern/ShFinder.cpp \
    ./Visitor Pattern/ShHitTester.cpp \
    ./Visitor Pattern/ShMirror.cpp \
    ./Visitor Pattern/ShPrintVisitor.cpp \
    ./Visitor Pattern/ShRotater.cpp \
    ./Visitor Pattern/ShSnapPointFinder.cpp \
    ./Visitor Pattern/ShStretchVisitor.cpp \
    ./Visitor Pattern/ShTrimer.cpp \
    ./Visitor Pattern/ShVisitor.cpp \
    ./ActionHandler/ShActionHandler.cpp \
    ./ActionHandler/ShActionHandlerManager.cpp \
    ./ActionHandler/ShActionHandlerDecorator.cpp \
    ./ActionHandler/ShDefaultAction.cpp \
    ./ActionHandler/ShPlotAreaSelectAction.cpp \
    ./ActionHandler/DrawAction/ShDrawAction.cpp \
    ./ActionHandler/DrawAction/ShDrawArcAction.cpp \
    ./ActionHandler/DrawAction/ShDrawCircleAction.cpp \
    ./ActionHandler/DrawAction/ShDrawLineAction.cpp \
    ./ActionHandler/DrawAction/ShDrawPolyLineAction.cpp \
    ./ActionHandler/TemporaryAction/ShDragSelectAction.cpp \
    ./ActionHandler/TemporaryAction/ShPanMoveAction.cpp \
    ./ActionHandler/TemporaryAction/ShStretchTemporaryAction.cpp \
    ./ActionHandler/TemporaryAction/ShTemporaryAction.cpp \
    ./ActionHandler/ModifyAction/ShModifyAction.cpp \
    ./ActionHandler/ModifyAction/ShModifyCopyAction.cpp \
    ./ActionHandler/ModifyAction/ShModifyEraseAction.cpp \
    ./ActionHandler/ModifyAction/ShModifyExtendAction.cpp \
    ./ActionHandler/ModifyAction/ShModifyMirrorAction.cpp \
    ./ActionHandler/ModifyAction/ShModifyMoveAction.cpp \
    ./ActionHandler/ModifyAction/ShModifyRotateAction.cpp \
    ./ActionHandler/ModifyAction/ShModifyStretchAction.cpp \
    ./ActionHandler/ModifyAction/ShModifyTrimAction.cpp \
    ./FactoryMethod/ShCreatorActionFactory.cpp \
    ./FactoryMethod/ShCreatorActionDecoratorFactory.cpp \
    ./FactoryMethod/ShCreatorObjectSnapFactory.cpp \
    ./FactoryMethod/ShCreatorViewDrawFactory.cpp \
    ./FactoryMethod/ShCreatorViewUpdateFactory.cpp \
    ./Singleton Pattern/ShChangeManager.cpp \
    ./Singleton Pattern/ShColorComboList.cpp \
    ./Singleton Pattern/ShDraftManager.cpp \
    ./Singleton Pattern/ShLineStyleComboList.cpp \
    ./Singleton Pattern/ShPrinterManager.cpp \
    ./Singleton Pattern/ShWidgetManager.cpp \
    ./Command Pattern/ShCommand.cpp \
    ./Command Pattern/ShRedoTaker.cpp \
    ./Command Pattern/ShUndoTaker.cpp \
    ./Command Pattern/Entity Command/ShAddEntityCommand.cpp \
    ./Command Pattern/Entity Command/ShChangeEntityLayerCommand.cpp \
    ./Command Pattern/Entity Command/ShChangeEntityPropertyDataCommand.cpp \
    ./Command Pattern/Entity Command/ShCopyEntityCommand.cpp \
    ./Command Pattern/Entity Command/ShDeleteEntityCommand.cpp \
    ./Command Pattern/Entity Command/ShExtendEntityCommand.cpp \
    ./Command Pattern/Entity Command/ShMirrorEntityCommand.cpp \
    ./Command Pattern/Entity Command/ShMoveEntityCommand.cpp \
    ./Command Pattern/Entity Command/ShRotateEntityCommand.cpp \
    ./Command Pattern/Entity Command/ShStretchEntityCommand.cpp \
    ./Command Pattern/Entity Command/ShTrimEntityCommand.cpp \
    ./Command Pattern/UI Command/ShChangeCurrentLayerCommand.cpp \
    ./Command Pattern/UI Command/ShChangeLayerDataCommand.cpp \
    ./Command Pattern/UI Command/ShChangePropertyDataCommand.cpp \
    ./Command Pattern/UI Command/ShCreateLayerCommand.cpp \
    ./Command Pattern/UI Command/ShDeleteLayerCommand.cpp \
    ./Command Pattern/UI Command/ShMoveViewCommand.cpp \
    ./Strategy Pattern/ShButtonWithMenuPopupStragety.cpp \
    ./Strategy Pattern/ShChangeCurrentActionStrategy.cpp \
    ./Strategy Pattern/ShObjectSnapStrategy.cpp \
    ./Strategy Pattern/ShSearchEntityStrategy.cpp \
    ./Strategy Pattern/ShViewDrawStrategy.cpp \
    ./Strategy Pattern/ShViewNotifyEventUpdateStrategy.cpp \
    ./Facade Pattern/ShCadFacade.cpp
RESOURCES += shcad.qrc
